-- ============================================================================
-- QB-CARGOHEIST - ADMIN QUERIES
-- Useful SQL queries for server administrators
-- ============================================================================

-- ============================================================================
-- PLAYER MANAGEMENT
-- ============================================================================

-- View a specific player's stats
SELECT 
  h.citizenid,
  h.heat_level,
  h.total_heists,
  h.successful_heists,
  h.failed_heists,
  ROUND((h.successful_heists / h.total_heists * 100), 2) as success_rate,
  h.total_earned,
  h.last_heist
FROM cargo_heist_heat h
WHERE h.citizenid = 'ABC12345'; -- Replace with actual citizenid

-- Reset a player's cooldown
DELETE FROM cargo_heist_cooldowns WHERE citizenid = 'ABC12345';

-- Reset a player's heat level
UPDATE cargo_heist_heat 
SET heat_level = 0, heat_points = 0 
WHERE citizenid = 'ABC12345';

-- Ban a player from heists (full schema only)
INSERT INTO cargo_heist_blacklist (citizenid, reason, banned_by, expires_at)
VALUES ('ABC12345', 'Exploiting', 'AdminName', NULL); -- NULL = permanent

-- Unban a player (full schema only)
UPDATE cargo_heist_blacklist 
SET is_active = 0 
WHERE citizenid = 'ABC12345';

-- View all banned players (full schema only)
SELECT * FROM cargo_heist_blacklist WHERE is_active = 1;

-- ============================================================================
-- HEIST MONITORING
-- ============================================================================

-- View currently active heists (full schema only)
SELECT 
  heist_id,
  leader_citizenid,
  cargo_id,
  approach_method,
  status,
  cargo_condition,
  TIMESTAMPDIFF(MINUTE, started_at, NOW()) as duration_minutes
FROM cargo_heist_active
WHERE status NOT IN ('completed', 'failed');

-- View available cargo
SELECT 
  cargo_id,
  cargo_type,
  current_value,
  security_level,
  is_active,
  is_claimed,
  available_end
FROM cargo_heist_intel
WHERE is_active = 1 AND is_claimed = 0
ORDER BY available_end ASC;

-- View recent heist completions (last 24 hours)
SELECT 
  heist_id,
  leader_citizenid,
  cargo_type,
  approach_method,
  success,
  final_payout,
  completion_time,
  heist_timestamp
FROM cargo_heist_history
WHERE heist_timestamp > DATE_SUB(NOW(), INTERVAL 24 HOUR)
ORDER BY heist_timestamp DESC;

-- Count heists by success/failure today
SELECT 
  success,
  COUNT(*) as count,
  SUM(final_payout) as total_payout
FROM cargo_heist_history
WHERE DATE(heist_timestamp) = CURDATE()
GROUP BY success;

-- ============================================================================
-- STATISTICS & ANALYTICS
-- ============================================================================

-- Top 10 earners (all time)
SELECT 
  h.citizenid,
  h.total_earned,
  h.total_heists,
  h.successful_heists,
  ROUND((h.successful_heists / h.total_heists * 100), 2) as success_rate
FROM cargo_heist_heat h
ORDER BY h.total_earned DESC
LIMIT 10;

-- Most popular cargo types
SELECT 
  cargo_type,
  COUNT(*) as times_attempted,
  SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as times_successful,
  ROUND(AVG(final_payout), 0) as avg_payout
FROM cargo_heist_history
GROUP BY cargo_type
ORDER BY times_attempted DESC;

-- Ground vs Air approach statistics
SELECT 
  approach_method,
  COUNT(*) as total_attempts,
  SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as successful,
  ROUND(AVG(final_payout), 0) as avg_payout,
  ROUND(AVG(completion_time), 0) as avg_time_seconds
FROM cargo_heist_history
GROUP BY approach_method;

-- Heist activity by hour of day
SELECT 
  HOUR(heist_timestamp) as hour_of_day,
  COUNT(*) as heist_count
FROM cargo_heist_history
WHERE heist_timestamp > DATE_SUB(NOW(), INTERVAL 7 DAY)
GROUP BY HOUR(heist_timestamp)
ORDER BY hour_of_day;

-- Total money generated by heists
SELECT 
  SUM(final_payout) as total_money_paid,
  COUNT(*) as total_heists,
  ROUND(AVG(final_payout), 0) as avg_payout
FROM cargo_heist_history
WHERE success = 1;

-- Players with highest heat levels
SELECT 
  citizenid,
  heat_level,
  total_heists,
  last_heist
FROM cargo_heist_heat
WHERE heat_level > 0
ORDER BY heat_level DESC, total_heists DESC
LIMIT 20;

-- ============================================================================
-- ECONOMY BALANCING
-- ============================================================================

-- Average payout by cargo type and approach
SELECT 
  cargo_type,
  approach_method,
  COUNT(*) as attempts,
  ROUND(AVG(final_payout), 0) as avg_payout,
  MIN(final_payout) as min_payout,
  MAX(final_payout) as max_payout
FROM cargo_heist_history
WHERE success = 1
GROUP BY cargo_type, approach_method
ORDER BY cargo_type, approach_method;

-- Success rates by security level
SELECT 
  ci.security_level,
  COUNT(*) as attempts,
  SUM(CASE WHEN hh.success = 1 THEN 1 ELSE 0 END) as successful,
  ROUND((SUM(CASE WHEN hh.success = 1 THEN 1 ELSE 0 END) / COUNT(*) * 100), 2) as success_rate
FROM cargo_heist_history hh
JOIN cargo_heist_intel ci ON hh.cargo_id = ci.cargo_id
GROUP BY ci.security_level
ORDER BY ci.security_level;

-- Intel acquisition methods (full schema only)
SELECT 
  intel_source,
  COUNT(*) as times_used,
  ROUND(AVG(intel_quality), 2) as avg_quality,
  ROUND(AVG(cost_paid), 0) as avg_cost
FROM cargo_heist_intel_acquired
GROUP BY intel_source
ORDER BY times_used DESC;

-- ============================================================================
-- MAINTENANCE & CLEANUP
-- ============================================================================

-- Clean up expired cargo intel manually
UPDATE cargo_heist_intel
SET is_active = 0
WHERE available_end < NOW() AND is_active = 1;

-- Delete very old cargo intel (older than 7 days)
DELETE FROM cargo_heist_intel
WHERE available_end < DATE_SUB(NOW(), INTERVAL 7 DAY);

-- Clean up expired cooldowns
DELETE FROM cargo_heist_cooldowns 
WHERE cooldown_until < NOW();

-- Delete old heist history (older than 30 days)
DELETE FROM cargo_heist_history 
WHERE heist_timestamp < DATE_SUB(NOW(), INTERVAL 30 DAY);

-- Clean up old intel acquisition records (full schema only)
DELETE FROM cargo_heist_intel_acquired
WHERE expires_at < DATE_SUB(NOW(), INTERVAL 7 DAY);

-- Manually decay heat for all players
UPDATE cargo_heist_heat
SET heat_level = GREATEST(0, heat_level - 1)
WHERE heat_level > 0;

-- Reset all cooldowns (emergency use only)
TRUNCATE TABLE cargo_heist_cooldowns;

-- ============================================================================
-- TESTING & DEBUGGING
-- ============================================================================

-- Create test cargo intel
INSERT INTO cargo_heist_intel 
(cargo_id, cargo_type, base_value, current_value, location, security_level, npc_guards, available_start, available_end) 
VALUES 
('TEST_' || UNIX_TIMESTAMP(), 'electronics', 100000, 100000, 'LSIA', 1, 2, NOW(), DATE_ADD(NOW(), INTERVAL 2 HOUR));

-- View all tables and row counts
SELECT 
  TABLE_NAME,
  TABLE_ROWS,
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024, 2) AS 'Size_MB'
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME LIKE 'cargo_heist_%'
ORDER BY TABLE_NAME;

-- Check for orphaned records (intel without matching history)
SELECT ci.cargo_id, ci.cargo_type, ci.is_claimed
FROM cargo_heist_intel ci
LEFT JOIN cargo_heist_history hh ON ci.cargo_id = hh.cargo_id
WHERE ci.is_claimed = 1 AND hh.cargo_id IS NULL;

-- Check for players on cooldown
SELECT 
  citizenid,
  heist_type,
  cooldown_until,
  TIMESTAMPDIFF(MINUTE, NOW(), cooldown_until) as minutes_remaining
FROM cargo_heist_cooldowns
WHERE cooldown_until > NOW()
ORDER BY cooldown_until ASC;

-- View event scheduler status
SHOW VARIABLES LIKE 'event_scheduler';

-- View active events
SHOW EVENTS WHERE Db = DATABASE();

-- ============================================================================
-- LEADERBOARD QUERIES (Full Schema Only)
-- ============================================================================

-- Overall leaderboard (by earnings)
SELECT 
  citizenid,
  player_name,
  total_earned,
  successful_heists,
  success_rate,
  highest_single_payout
FROM cargo_heist_leaderboard
ORDER BY total_earned DESC
LIMIT 25;

-- Fastest completion times
SELECT 
  citizenid,
  player_name,
  fastest_completion as seconds,
  CONCAT(FLOOR(fastest_completion / 60), 'm ', MOD(fastest_completion, 60), 's') as time_formatted
FROM cargo_heist_leaderboard
WHERE fastest_completion < 999999
ORDER BY fastest_completion ASC
LIMIT 10;

-- Most active pilots
SELECT 
  citizenid,
  player_name,
  times_as_pilot,
  air_heists,
  total_earned
FROM cargo_heist_leaderboard
WHERE times_as_pilot > 0
ORDER BY times_as_pilot DESC
LIMIT 10;

-- Best success rates (minimum 10 heists)
SELECT 
  citizenid,
  player_name,
  successful_heists,
  total_heists,
  success_rate,
  total_earned
FROM cargo_heist_leaderboard
WHERE total_heists >= 10
ORDER BY success_rate DESC
LIMIT 10;

-- Update player name in leaderboard
UPDATE cargo_heist_leaderboard
SET player_name = 'John Doe'
WHERE citizenid = 'ABC12345';

-- ============================================================================
-- CONFIGURATION (Full Schema Only)
-- ============================================================================

-- View all config settings
SELECT * FROM cargo_heist_config ORDER BY config_key;

-- Update config value
UPDATE cargo_heist_config
SET config_value = '5'
WHERE config_key = 'require_cops';

-- Add new config entry
INSERT INTO cargo_heist_config (config_key, config_value, value_type, description)
VALUES ('max_heat_level', '5', 'number', 'Maximum heat level a player can reach')
ON DUPLICATE KEY UPDATE config_value = VALUES(config_value);

-- ============================================================================
-- REPORTS
-- ============================================================================

-- Daily Activity Report
SELECT 
  DATE(heist_timestamp) as date,
  COUNT(*) as total_heists,
  SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as successful,
  SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) as failed,
  SUM(final_payout) as total_payout,
  COUNT(DISTINCT leader_citizenid) as unique_leaders
FROM cargo_heist_history
WHERE heist_timestamp >= DATE_SUB(NOW(), INTERVAL 7 DAY)
GROUP BY DATE(heist_timestamp)
ORDER BY date DESC;

-- Player Activity Report (individual)
SELECT 
  h.citizenid,
  h.heat_level,
  h.total_heists,
  h.successful_heists,
  h.failed_heists,
  ROUND((h.successful_heists / h.total_heists * 100), 2) as success_rate,
  h.total_earned,
  h.last_heist,
  c.cooldown_until
FROM cargo_heist_heat h
LEFT JOIN cargo_heist_cooldowns c ON h.citizenid = c.citizenid
WHERE h.citizenid = 'ABC12345';

-- Economic Impact Report (last 7 days)
SELECT 
  'Last 7 Days' as period,
  COUNT(*) as total_heists,
  SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as successful,
  SUM(final_payout) as money_generated,
  ROUND(AVG(final_payout), 0) as avg_payout,
  COUNT(DISTINCT leader_citizenid) as unique_players
FROM cargo_heist_history
WHERE heist_timestamp >= DATE_SUB(NOW(), INTERVAL 7 DAY);

-- ============================================================================
-- PERFORMANCE OPTIMIZATION
-- ============================================================================

-- Analyze table performance
ANALYZE TABLE 
  cargo_heist_intel,
  cargo_heist_history,
  cargo_heist_cooldowns,
  cargo_heist_heat;

-- Optimize tables (run during low traffic times)
OPTIMIZE TABLE 
  cargo_heist_intel,
  cargo_heist_history,
  cargo_heist_cooldowns,
  cargo_heist_heat;

-- Check index usage
SHOW INDEX FROM cargo_heist_history;

-- View slow queries related to heists
-- (Requires slow query log enabled in MySQL)
-- SET GLOBAL slow_query_log = 'ON';
-- SET GLOBAL long_query_time = 2;

-- ============================================================================
-- EMERGENCY PROCEDURES
-- ============================================================================

-- Cancel all active heists (full schema only)
DELETE FROM cargo_heist_active;

-- Reset all cargo to available
UPDATE cargo_heist_intel
SET is_claimed = 0
WHERE is_claimed = 1;

-- Clear all cooldowns (use with caution)
TRUNCATE TABLE cargo_heist_cooldowns;

-- Reduce all heat levels by 1
UPDATE cargo_heist_heat
SET heat_level = GREATEST(0, heat_level - 1);

-- Backup critical data before maintenance
CREATE TABLE cargo_heist_history_backup AS SELECT * FROM cargo_heist_history;
CREATE TABLE cargo_heist_heat_backup AS SELECT * FROM cargo_heist_heat;

-- Restore from backup
-- INSERT INTO cargo_heist_history SELECT * FROM cargo_heist_history_backup;
-- INSERT INTO cargo_heist_heat SELECT * FROM cargo_heist_heat_backup;

-- ============================================================================
-- NOTES FOR ADMINISTRATORS
-- ============================================================================

/*
BEST PRACTICES:
1. Run cleanup queries during low server activity
2. Always backup before making bulk changes
3. Monitor table sizes regularly
4. Check for orphaned records weekly
5. Optimize tables monthly

PERFORMANCE TIPS:
- Keep history table under 100k rows (archive old data)
- Clean up expired intel daily
- Monitor index usage with EXPLAIN queries
- Use views for complex reports instead of repeated queries

SECURITY:
- Never share admin queries with players
- Use prepared statements in your application
- Limit direct database access
- Regular backups are essential
*/
